# Generated by Django 2.2.3 on 2019-11-24 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_bd',
            name='id',
        ),
        migrations.AlterField(
            model_name='image_bd',
            name='image_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.Films'),
            preserve_default=False,
        ),
    ]
